export enum SectorEnum {
    todos = 'Todos',
    blockchain = 'Blockchain',
    iot = 'IOT',
    bigData = 'Big Data',
    tech = 'Tech',
    economia_naranja = 'Economía Naranja',
    edtech = 'Edtech',
    foodtech = 'Foodtech',
    agritech = 'Agritech',
    health_tech = 'Health Tech',
    intraemprendimiento = 'Intraemprendimiento',
    legaltech = 'Legaltech',
    proptech = 'Proptech',
    movilidad_y_nuevas_energías = 'Movilidad y nuevas energías',
    fintech = 'Fintech',
    retail_marketplace_Ecommerce = 'Retail/ marketplace/ E-commerce',
    saas = 'SAAS',
    cloud = 'Cloud',
    ia = 'IA',
}
