
export const listasEmpleo = [
	'CTO',
	'CEO',
	'CFO',
	'Desarrollador/a front',
    'Desarrollador/a backend',
    'Fullstack',
    'Project Manger',
    'Marketing',
    'Data analyst',
    'Contador/a',
    'Comercial',
    'Comunicador/a',
    'Abogado/a',
    'Ciberseguridad',
    'Diseñador',
    'UX/UI',
    'Business analyst',
    'Planner',
    'Agile Coach',
    'CRM analyts',
    'Operation',
    'Growth',
    'Financial analyst',
    'Data scientist',
    'KAM',
    'Comunity Manager',
    'Hunter',
    'HR vp',
    'Hr analyst',
    'Hr recruiter',

];